language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"

install:
  - pip install -r requirements.txt

script:
  - pytest barry_energy_api/test.py